version: 2
updates:
  - package-ecosystem: "pip"
    directory: "./"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "image_generation/stable_diffusion_1_5/cpp/scripts/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "image_generation/lcm_dreamshaper_v7/cpp/scripts/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "text_generation/causal_lm/cpp/"
    schedule:
      interval: "weekly"
